version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./gradlew test

  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: ./gradlew build
      - store_artifacts:
          path: build/libs/

  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Replace secret key in application.properties
          command: sed -i "s|\${MY_SECRET_KEY}|${MY_SECRET_KEY}|g" src/main/resources/application.properties

      - run:
          name: Print MongoDB URI
          command: echo "MongoDB URI: $MY_SECRET_KEY"

      - run:
          name: Setup Gradle
          command: ./gradlew wrapper --gradle-version 8.5

      - run:
          name: Build with Gradle 8.5
          command: ./gradlew build

      - run:
          name: deploy
          command: ./deploy.sh

workflows:
  version: 2
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
