version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./gradlew test

  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt

  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Replace secret key in application.properties
          command: sed -i "s|\${MY_SECRET_KEY}|${MY_SECRET_KEY}|g" src/main/resources/application.properties

      - run:
          name: Setup Gradle
          command: ./gradlew wrapper --gradle-version 8.5

      - run:
          name: Build with Gradle 8.5
          command: ./gradlew build

      - run:
          name: deploy
          command: ./deploy.sh

      - run:
          name: Deploy to website
          command: |
            # Example command to deploy to a website using rsync
            rsync -avz --delete build/ user@yourwebsite.com:/path/to/website/

workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
